export enum PokemonType {
  NORMAL = "Normal",
  FIRE = "Fogo",
  WATER = 'Água',
  GRASS = 'Grama',
  FLYING = 'Voador',
  FIGHTING = 'Lutador',
  POISON = 'Veneno',
  ELETRIC = 'Elétrico',
  GROUND = 'Terra',
  ROCK = 'Pedra',
  PSYCHIC = 'Psíquico',
  ICE = 'Gelo',
  BUG = 'Inseto',
  GHOST = 'Fantasma',
  STEEL = 'Ferro',
  DRAGON = 'Dragão',
  DARK = 'Sombrio',
  FAIRY = 'Fada',
}